name: UH-Phonebook CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
    build_lint_test:
        name: Build, Lint & Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            
            - name: Install dependencies (frontend & backend)
              run: |
                cd frontend
                npm install
                cd ../backend
                npm install

            - name: Lint frontend
              run: |
                cd frontend
                npm run lint
    
            - name: Lint backend
              run: |
                cd backend
                npm run lint
    
            - name: Run backend tests
              run: |
                cd backend
                npm run test
    
            - name: Run frontend tests
              run: |
                cd frontend
                npm run test

    playwright_test:
        name: Playwright Tests
        runs-on: ubuntu-latest
        timeout-minutes: 5
        env:
            PORT: 3001
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: '20'

          - name: Install dependencies (frontend & backend)
            run: |
              cd frontend
              npm install
              cd ../backend
              npm install

          - name: Install dependecies (Playwright)
            run: npm ci
            
          - name: Install Playwright Browsers
            run: npx playwright install --with-deps
          
          - name: Run Playwright tests
            run: npx playwright test

          - uses: actions/upload-artifact@v4
            if: ${{ !cancelled() }}
            with:
              name: playwright-report
              path: playwright-report/
              retention-days: 30

    tag_releases:
      name: Tag Releases
      runs-on: ubuntu-latest
      permissions:
        contents: write
      needs: [build_lint_test, playwright_test]
      if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
          env:
            DEFAULT_BUMP: 'patch'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DRY_RUN: false

    deploy:
      name: Deploy to Fly.io
      runs-on: ubuntu-latest
      needs: [build_lint_test, playwright_test, tag_releases]
      concurrency: deploy-group # Prevents multiple deployments at the same time
      if: ${{ github.event_name == 'push' }}
      steps:
        - uses: actions/checkout@v4
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}